### ISSUE TITLE
No return from 'login' listener.

### ISSUE THREAD

**Issue by diogoamorim2** [AppWerft/Ti.GoogleSignIn#10]
Hi, I follow your example code in one fresh project, and  work's perfect, but the listener 'login' always  returning user log, did't I not doing rigth?

**Comment by chmiiller** [comment]
Hey @diogoamorim2 are you in the TiSlack? If not, try here: https://ti-slack.slack.com and we can chat there. Where are you from? Your name sounds Brazilian or Portuguese for me =) If so, podemos conversar em português!

**Comment by diogoamorim2** [comment]
Sim, sou BR , não faço parte desde time no slack, eu poderia participar deste time? Caso positivo, meu e-mail é "darkforest_2@hotmail.com". Muito Obrigado.

**Comment by chmiiller** [comment]
adiocionei! Conversamos por lá então!

**Comment by Sophrinix** [comment]
for 6.0.2.GA, 6.1.1.GA, 6.1.2.GA I am having this issue as well

**Comment by Sophrinix** [comment]
I figured this out:
Turns out you need to absolutely make sure you use the right key. Also use double quotes, not single quotes. 
I have no idea why this mattered, but it appears to have.
Best of luck @diogoamorim2

**Comment by diogoamorim2** [comment]
Hi @Sophrinix , @chmiiller help me out whit this issue and everthing work as expected! Thx for your reply.
