### ISSUE TITLE
Conflict with google-play-services-base.jar

### ISSUE THREAD

**Issue by rotechcr** [AppWerft/Ti.GoogleSignIn#11]
I have installed this module, but it's giving conflicts with ti.map and ti.cloudpush in relation to the google-play-services-base.jar.

I have tried in many ways to fix it, but no success.
I know this problem is very common, can someone help me telling how can I fix that?

Regards,

**Comment by AppWerft** [comment]
Yes, you have to ensure that all jars in project with same name has the same version.

**Comment by chmiiller** [comment]
Yes, this could happen. Better have a look at this issue: https://github.com/AppWerft/Ti.GoogleSignIn/issues/5. I explain how to solve it. Hope it works for you as well!

**Comment by rotechcr** [comment]
Thanks for the support. I have run the Google Play Service Lite script, removed all the google-play-services-*.jar JARS from the ti.cloudpush, ti.map and ti.googlesignin. And then placed in each one the generated full version jar, but at the compile time it got stuck in "Running dexer:"

Some help? A specific version? Some skipped step?

Thanks a lot!

**Comment by AppWerft** [comment]
The best way is to go in you SDK. Then ./extras/google/m2repository/com/google/android/gms/. Here you find i.e play-services-maps/  Choose newest version 
The aar you open and extract the jar (renaming!) in .pom you find the dependencies and so on. all Jars you copy to lib folder. Its all.
