### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by rjaimes95** [AppWerft/Ti.GoogleSignIn#13]
Hello.
I followed your guide in this repo. I had some issues with the map but a coworker solved them.
Now we get an error in exec time with:
Requested module not found: ti.googlesignin
Exception occurred at ti:/module.js:303: Uncaught Error: Requested module not found: ti.googlesignin.
We call the module like this:
`var GoogleIn = require('ti.googlesignin');`
I hope you can help.

**Comment by chmiiller** [comment]
Are you sure you have included the module in your "modules" folder?
Also that you included the module in your `tiapp.xml` file like this:
`<modules>
<module platform="android">ti.googlesignin</module>
</modules>`
?

**Comment by rjaimes95** [comment]
Thanks for your answer. We interrupted this part of our project and removed your module temporarily, so I'm not positive about that but I think we added the module to the correct folder and we also modified the tiapp.xml accordingly. We will probably return to this part later and come back to this issue if we face the same problem.
Thank you again.

**Comment by SamBellerose** [comment]
When you say «Unpack the module» what files do you mean @chmiiller ? I'm new to Titanium and have the same error.

I've added the two files named GoogleServices.java and GooglesigninModule inside modules/android/ti/googlesignin, but I get the error "Module is not supported by Titanium SDK 6.1.2.GA", is there something that I'm doing wrong?

**Comment by chmiiller** [comment]
Hi @rjaimes95 are you still using this module? It does work now 😬. Otherwise I'm going to just close this issue. Let me know if I can help you installing and setting it up!
Bests
