### ISSUE TITLE
Error event being called after signin

### ISSUE THREAD

**Issue by SamBellerose** [AppWerft/Ti.GoogleSignIn#16]
I've followed all the instructions, I can sign in, but right after signin the error event is being called.

When I log the error, here's what I have

{"type":"error","source":{"apiName":"Ti.Module","bubbleParent":true,"invocationAPIs":[],"_events":{"connect":{},"error":{},"login":{}}},"message":null,"status":10,"success":false,"bubbles":false,"cancelBubble":false}

I'm using Titanium SDK 6.1.1.GA
I'm using a Web application client ID

Any idea what could cause this? Could it be a configuration issue?

**Comment by yankovalera** [comment]
hi Sam,

I'm having this problem, how do you manage to solve it?

Regards
