### ISSUE TITLE
Module not working on Titanium SDK 7.0.0 & 7.0.1

### ISSUE THREAD

**Issue by guillefixx** [AppWerft/Ti.GoogleSignIn#21]
Console error:

> [ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/Auth;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/Auth$AuthCredentialsOptions;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/Auth$AuthCredentialsOptions$Builder;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/credentials/Credential;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/credentials/Credential$Builder;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/credentials/CredentialPickerConfig;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/credentials/CredentialPickerConfig$Builder;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/credentials/CredentialPickerConfig$Prompt;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/credentials/CredentialRequest;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
[ERROR] :  	at com.android.dx.command.dexer.Main.runDx(Main.java:289)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:247)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:94)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
[ERROR] :  	... 4 more
[ERROR] Application Installer abnormal process termination. Process exit value was 1

I tried adding ti.playservices module to my tiapp.xml but I'm getting the same error.

By the way, before showing the error above, the console also shows this:

> [WARN] :   The module ti.googlesignin does not support the ABI: arm64-v8a
[WARN] :   It only supports the following ABIs: armeabi-v7a, x86
[WARN] :   Your application will most likely encounter issues

**Comment by yankovalera** [comment]
Hi, I'm getting exact error. Are there any workarounds for this?

Regards

**Comment by m1ga** [comment]
@guillefixx You have to recompile the module using `ti.playservices` and remove all jars from the /lib folder. Did you do that or did you just add the `ti.playservices` to your app?

**Comment by AppWerft** [comment]
You strip all jars from lib folder (of your module) and add https://github.com/appcelerator-modules/ti.playservices to the app

**Comment by guillefixx** [comment]
@AppWerft I stripped all the jars from the module and then I added the ti.playservices to my app, but it still doesn't work.

My console is throwing this error:

> [ERROR] :  TiApplication: (main) [8,693] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.appname-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.appname-1/lib/x86, /data/app/com.example.appname-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libti.googlesignin.so"; Titanium 7.0.1,2017/12/18 10:42,undefined
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.appname-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.appname-1/lib/x86, /data/app/com.example.appname-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libti.googlesignin.so"
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:1530)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] :  TiApplication: 	at com.example.appname.AppnameApplication.onCreate(AppnameApplication.java:50)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:154)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by AppWerft** [comment]
You have stripped too much. Now the main so is missing.

**Comment by guillefixx** [comment]
I've found what caused the crash. Apparently, the zipped module I downloaded (ti.googlesignin-android-2.0.0.zip) didn't have the arm64-v8a folder inside /libs.

**Comment by AppWerft** [comment]
Nice

**Comment by Hemantsolanki103** [comment]
@guillefixx, I compiled the module with new version 2.0.2, in these arm64-v8a available folder inside /libs. But I got the same issue mention below.

dlopen("/data/app-lib/com.devtest.app-1/libti.googlesignin.so") failed: dlopen failed: cannot locate symbol "_ZNSt3__112__next_primeEj" referenced by "libti.googlesignin.so"...
Thanks

**Comment by AppWerft** [comment]
In this case googlesignin.so calls an obfuscated method in close source jar

**Comment by Hemantsolanki103** [comment]
@AppWerft, Could you please provide help, What can I do to resolved this issue and use the module perfectly? Please help to resolved this issue.

**Comment by guillefixx** [comment]
@yankovalera sent me a modified version which works:
[ti.googlesignin.zip](https://github.com/AppWerft/Ti.GoogleSignIn/files/1621733/ti.googlesignin.zip)
