### ISSUE TITLE
Error while used 3.0.0 version with Titanium 7

### ISSUE THREAD

**Issue by Hemantsolanki103** [AppWerft/Ti.GoogleSignIn#22]
Hi AppWerft,

I am getting error while I compile my code successfully with Titanium SDK 7.0.1. Error Mention below:

Error:

[ERROR] :  TiExceptionHandler: (main) [0,104445] - Message: Uncaught com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder
[ERROR] :  TiExceptionHandler: (main) [1,104446] - Source:     Google.initialize({
[ERROR] :  V8Exception: Exception occurred at /alloy/controllers/Login.js:233: Uncaught com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder
[ERROR] :  V8Exception: com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder 

Please help me for that issue.

Thanks & Regards,
Hemant

**Comment by prashantsaini1** [comment]
Did you include the `ti.playservices` module also? If yes, then a code snippet will be more helpful.

**Comment by Hemantsolanki103** [comment]
@prashantsaini1  Thanks for your great help. I did it with your solution. But Prashant I got one more problem when I user ti.cloudpush with ti.googlesignin and ti.playservice, application not compiled in Android, It stuck on Running Dexer in console log(Without any error message).
Could you please it once?

Thanks

**Comment by chmiiller** [comment]
Did you solve your problem? Maybe is has something to do of one of those modules still using its own version of playservices. Maybe you can update them and check if playservices are not conflicting.
