### ISSUE TITLE
Login Event not working when using a (Login with another user) option 

### ISSUE THREAD

**Issue by ashishSebu** [AppWerft/Ti.GoogleSignIn#26]
Hi,

TiSDK: 7.0.1.GA
iOS: 11
Module: 1.2.2

Steps to reproduce the error

1. Click on Google Login Button
2. On Google Login Page, click on 'Login with another user' button
3. Login using the a new credentials.
4. Google Login Page is closed, but the login event is not fired.

When I tried to repeat the same process on iOS 10 it worked and also if I try to login with any existing user that I have already logged and the User name is listed on the Google Page, I get the Login Event Listener in iOS 11 also.

**Comment by chmiiller** [comment]
Hi @ashishSebu thanks for reporting this, but this is the Android version repository. I would recommend you to open an [issue there](https://github.com/hansemannn/titanium-google-signin/issues) instead
