### ISSUE TITLE
App fails to build if this module is used with ti.map and ti.cloudpush

### ISSUE THREAD

**Issue by zarir** [AppWerft/Ti.GoogleSignIn#5]
`[ERROR] :  Failed to run dexer:

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/GoogleAuthUtil;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEvent;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/UserRecoverableAuthException;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/zze;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/TokenData;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/zzc;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEventsResponse;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/zza;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/zzd;

[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:

[ERROR] :  java.lang.RuntimeException: Translation has been interrupted

[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)

[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)

[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:275)

[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)

[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)

[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors

[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)

[ERROR] :  	... 4 more`

**Comment by AppWerft** [comment]
You use more the this module in your app?

**Comment by zarir** [comment]
Yes, I have used ti.map v3.0.1 (latest) and ti.cloudpush v4.0.3 (latest)

**Comment by AppWerft** [comment]
All the modules must use the same version of google-playservice.jar

**Comment by zarir** [comment]
Shall I directly replace the google-play-services.jar in /lib folder? What about google-play-service-auth-10.2.0.jar and google-play-services-auth-base-10.2.0.jar even these I need to replace?

**Comment by AppWerft** [comment]
The best is to use single jars for every function. With this you can better play with it.

**Comment by zarir** [comment]
How to go about it?

**Comment by AppWerft** [comment]
You have to extract the right ones from SDK/extras/google/m2repository/

**Comment by zarir** [comment]
I could find google-play-service-auth-10.2.0.jar and google-play-services.jar. What about google-play-services-auth-base-10.2.0.jar and google-play-services-basement-10.2.0.jar files?

**Comment by chmiiller** [comment]
hi @zarir, help is here!
I also had this problems with conflicting jars for this module and Urban Airship google play services.
I've been using this (amazing!) tool https://github.com/darkdukey/Google-Play-Service-Lite to fix it.
@AppWerft module is making use of some 10.1 play services classes and methods so the first thing you will have to do is to update your Google Repository on your Android SDK folder. Then with this tool linked you will be able to get a full and up-to-date google-play-services.jar. Actually, I've already made a PR on this repo https://github.com/darkdukey/Google-Play-Service-Lite/pull/6 with the last full .jar.
So what you have to do is to remove all .jars from the Google Sign in module and use this full jar. And use the same jar for every conflicting module.
Or as @AppWerft has suggested, you can use this tool to select what jars you will need.

**Comment by zarir** [comment]
@chmiiller This worked. Thanks

**Comment by chmiiller** [comment]
Great! Can you explain exactly what you have done to make it work before we close this issue? So other can fix their projects as well =)
Thanks

**Comment by zarir** [comment]
As @chmiiller mentioned I had to replace conflicting google-play-services.jar from multiple modules with one single jar file from [https://github.com/darkdukey/Google-Play-Service-Lite](https://github.com/darkdukey/Google-Play-Service-Lite). The steps are simple and easy to follow.

**Comment by chmiiller** [comment]
Glad that this helped!
