### ISSUE TITLE
Ti.GoogleSignIn can't build in 5.5.1

### ISSUE THREAD

**Issue by midoajax** [AppWerft/Ti.GoogleSignIn#7]
```shell
Titanium SDK
  SDK Version                 = 5.5.1.GA
  SDK Path                    = /Users/macbookpro/Library/Application Support/Titanium/mobilesdk/osx/5.5.1.GA
  Target Platform             = android
Command
  /usr/local/bin/node /Users/macbookpro/.appcelerator/install/6.2.0/package/node_modules/titanium/lib/titanium.js build run --platform android --log-level trace --sdk 5.5.1.GA --project-dir /Users/macbookpro/Documents/Appcelerator_WSNew/Googlesignin --target device --android-sdk /Users/macbookpro/Library/android-sdk-macosx --device-id 95a62647 --skip-js-minify --liveview --deploy-type development --no-colors --no-progress-bars --no-prompt --prompt-type socket-bundle --prompt-port 61376 --config-file /var/folders/vn/pk6vcszd5yg1x03ybxdr0pf40000gn/T/build-1495545647553.json --no-banner --project-dir /Users/macbookpro/Documents/Appcelerator_WSNew/Googlesignin
[WARN] :   Could not find a valid Titanium module id=ti.googlesignin version=latest platform=android deploy-type=development
[ERROR] :  Could not find all required Titanium Modules:
[ERROR] :     id: ti.googlesignin	 version: latest	 platform: android	 deploy-type: development
```

**Comment by AppWerft** [comment]
This happens if name in manifest != in module.

**Comment by midoajax** [comment]
wish manifest, when can i found it in my project please

**Comment by AppWerft** [comment]
the manifest inside module

**Comment by AppWerft** [comment]
it is right, please open with a text editor like vi.

**Comment by midoajax** [comment]
this is content for this file 

#
# this is your module manifest and used by Titanium
# during compilation, packaging, distribution, etc.
#
version: 1.1.3
apiversion: 3
architectures: armeabi-v7a x86
description: googlesignin
author: Rainer Schleevoigt
license: Apache
copyright: Copyright (c) 2017 by Rainer Schleevoigt

# these should not be edited
name: googlesignin
moduleid: ti.googlesignin
guid: d548b85b-bfcb-43c5-a13d-a63d148ba8a0
platform: android
minsdk: 6.0.1

**Comment by AppWerft** [comment]
It is OK.

**Comment by midoajax** [comment]
No i m changing this file to minsdk: 5.5.1.GA and doesn't work so please help

**Comment by varun0294** [comment]
Did you get it work for 5.5.1GA by changing in manifest ?

**Comment by chmiiller** [comment]
You will have to set `minsdk` to 5.5.1.GA, change the `architectures` and rebuild the module

**Comment by chmiiller** [comment]
But keep in mind that it is highly recommended to update your project to use one of latest versions of Titanium SDK like 6.1 for example

**Comment by SamBellerose** [comment]
I have the same thing, here's what my project looks like this https://imgur.com/a/5rZYw . Is the modules/android folder ok? Do I need more things in this folder?

**Comment by chmiiller** [comment]
This issue is 1 year old and the module seems to work just fine for modern Ti SDK versions (7.x). Closing it.
