### ISSUE TITLE
GoogleSignin with Production and developement 

### ISSUE THREAD

**Issue by AlokGupta007** [AppWerft/Ti.GoogleSignIn#8]
Hi,

This is not working for me. I am trying to create login but giving error.
Here is my client ID
Google.initialize({
	clientID : "578497211426-4272anhsnpu4bu80qv7detbgscpp8lql.apps.googleusercontent.com",
});

And the error is 
{"type":"error","source":{"bubbleParent":true,"apiName":"Ti.Module","invocationAPIs":[],"_events":{"connect":{},"error":{},"disconnect":{},"login":{}}},"message":null,"status":10,"success":false,"bubbles":false,"cancelBubble":false}

Not Getting why the error is coming. Please help me out this.

Thanks
Alok

**Comment by chmiiller** [comment]
Where did you get this clientID from? You should use the Web version from https://console.developers.google.com/apis/credentials
![screen shot 2017-06-14 at 17 23 04](https://user-images.githubusercontent.com/1013632/27140710-85f1f104-5126-11e7-88d9-60a8069528a1.png)

**Comment by AppWerft** [comment]
I think a server key.

**Comment by AlokGupta007** [comment]
Yes this is the server key. as shown in screenshot.

**Comment by chmiiller** [comment]
You shouldn't use "server key" you should use the "web client" key

**Comment by SamBellerose** [comment]
I have the same issue. @AlokGupta007 and @drachma were you able to fix this problem? I'm using a web client key also
